version: '3'

services:
  server:
    build: .
    image: server
    ports:
      - '${AUTH_SERVICE_PORT}:${AUTH_SERVICE_PORT}'
    command: npm run start
    volumes:
      - ./:/app
    depends_on:
      - db
      - redis
      - rabbitmq
  db:
    image: postgres:12.4
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - 'db-data:/var/lib/postgresql/data'
    ports:
      - '${POSTGRES_PORT}:5432'
  pgadmin:
    image: dpage/pgadmin4:4.25
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_LISTEN_PORT: 80
    ports:
      - '${PGADMIN_PORT}:80'
    volumes:
      - 'pgadmin-data:/var/lib/pgadmin'
    depends_on:
      - db
  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_ERLANG_COOKIE: ${RABBITMQ_ERLANG_COOKIE}
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    volumes:
      - 'rbmq-data:/var/lib/rabbitmq'
    ports:
      - '${RABBITMQ_UI_PORT}:15672'
      - '${RABBITMQ_PORT}:5672'
    depends_on:
      - redis
  redis:
    image: 'redis:alpine'
    ports:
      - '${REDIS_PORT}:6379'
  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      REDIS_HOSTS: ${REDIS_URI}
    ports:
      - '${REDIS_COMMANDER_PORT}:8081'
    depends_on:
      - redis

volumes:
  db-data:
  pgadmin-data:
  rbmq-data:
